name = "expairiment-com"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "expairiment-leads"
database_id = "88afb711-5651-4992-b262-49465f0c90fc"
